# Notebook 4: Pandas Basics

## 1. Introduction to Pandas

Pandas is a Python library used for data manipulation and data analysis. It helps us organize, clean, filter, and analyze structured data.

Pandas provides two main data structures:

- **Series:** A one-dimensional labeled data structure.
- **DataFrame:** A two-dimensional table with rows and columns.

Pandas is widely used in data science, business analytics, and machine learning.

### Real-world example
A shop can use Pandas to analyze product names, prices, sales, and customer details.

### Business example
A company can calculate total sales, compare product performance, and analyze monthly revenue.

### AI/ML example
An AI/ML engineer can use Pandas to load a dataset, handle missing values, select features, and prepare data before training a machine learning model.

In [2]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.3
NumPy version: 2.4.6

## 2. Why Do We Use Pandas?

Pandas makes it easier to work with structured data in rows and columns.

### Advantages
- Easy handling of tabular data.
- Supports missing-value detection and handling.
- Provides filtering, sorting, grouping, and aggregation.
- Supports CSV, Excel, JSON, and other data formats.
- Integrates with NumPy, Matplotlib, and machine learning libraries.
- Helps prepare datasets for AI/ML models.

### Limitations
- Large datasets may require considerable memory.
- Some operations can be slower than optimized NumPy operations.
- Complex data processing still requires an understanding of programming and statistics.

### Common Applications
- Data cleaning and preprocessing.
- Business reporting and sales analysis.
- Financial data analysis.
- Customer behavior analysis.
- Machine learning data preparation.

## 3. Pandas Series

A Series is a one-dimensional labeled array that can store values such as integers, floating-point numbers, strings, and other Python objects.

Each value in a Series has an associated index label.

### Real-World Example
A Series can store the marks obtained by students in an examination.

### Syntax
`pd.Series(data, index=index_labels)`

In [3]:
import pandas as pd

marks = pd.Series([85, 90, 78, 92, 88])

print(marks)

0    85
1    90
2    78
3    92
4    88
dtype: int64

### Explanation:
- The values are the students' marks.
- The numbers on the left are the default index labels.
- int64 indicates the integer data type used for the values.

In [4]:
marks = pd.Series(
    [85, 90, 78, 92, 88],
    index=["Anu", "Ravi", "Priya", "Kiran", "Sneha"]
)

print(marks)
print("\nMarks of Priya:", marks["Priya"])
print("Average marks:", marks.mean())

Anu      85
Ravi     90
Priya    78
Kiran    92
Sneha    88
dtype: int64

Marks of Priya: 78
Average marks: 86.6

## 4. Pandas DataFrame

A DataFrame is a two-dimensional labeled data structure consisting of rows and columns. Different columns can contain different data types.

It is similar to a spreadsheet or a database table.

### Real-World Example
A student database can contain student IDs, names, ages, and marks.

### Business Example
A sales DataFrame can store product names, quantities sold, prices, and revenue.

### AI/ML Example
A machine learning dataset can contain input features such as age, income, and experience, along with a target column such as whether a customer purchases a product.

In [5]:
import pandas as pd

data = {
    "Name": ["Anu", "Ravi", "Priya", "Kiran", "Sneha"],
    "Age": [20, 21, 20, 22, 21],
    "Marks": [85, 90, 78, 92, 88],
    "Department": ["AI", "CSE", "AI", "ECE", "CSE"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks Department
0    Anu   20     85         AI
1   Ravi   21     90        CSE
2  Priya   20     78         AI
3  Kiran   22     92        ECE
4  Sneha   21     88        CSE

### Explanation:
- Each dictionary key becomes a column name.
- Each list contains the values for that column.
- Each row represents one student.
- Pandas automatically assigns an index starting from zero.

## 5. Basic DataFrame Inspection

Pandas provides several methods and attributes to understand the structure and contents of a dataset.

- `head()` displays the first rows.
- `tail()` displays the last rows.
- `shape` returns the number of rows and columns.
- `columns` returns column labels.
- `index` returns row labels.
- `dtypes` shows the data type of each column.
- `info()` provides a summary of the DataFrame.
- `describe()` provides descriptive statistics for numeric columns.

In [6]:
print("First 3 rows:")
display(df.head(3))

print("Last 2 rows:")
display(df.tail(2))

print("Shape:", df.shape)

print("Columns:", df.columns.tolist())

print("Index:", df.index)

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

print("\nDescriptive statistics:")
display(df.describe())

First 3 rows:

    Name  Age  Marks Department
0    Anu   20     85         AI
1   Ravi   21     90        CSE
2  Priya   20     78         AI

Last 2 rows:

    Name  Age  Marks Department
3  Kiran   22     92        ECE
4  Sneha   21     88        CSE

Shape: (5, 4)
Columns: ['Name', 'Age', 'Marks', 'Department']
Index: RangeIndex(start=0, stop=5, step=1)

Data types:
Name            str
Age           int64
Marks         int64
Department      str
dtype: object

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Marks       5 non-null      int64
 3   Department  5 non-null      str
dtypes: int64(2), str(2)
memory usage: 327.0 bytes

Descriptive statistics:

            Age      Marks
count   5.00000   5.000000
mean   20.80000  86.600000
std     0.83666   5.458938
min    20.00000  78.000000
25%    20.00000  85.000000
50%    21.00000  88.000000
75%    21.00000  90.000000
max    22.00000  92.000000

### Output explanation:
- shape returns (5, 4) because the dataset has five rows and four columns.
- columns.tolist() returns ['Name', 'Age', 'Marks', 'Department'].
- dtypes identifies text and numeric columns.
- info() displays the number of non-null values and memory usage.
- describe() summarizes numeric columns using count, mean, standard deviation, minimum, quartiles, and maximum.

## 6. Data Types in Pandas

Data types describe the kind of values stored in each column.

Common Pandas data types include:

- `int64`: Integer values.
- `float64`: Decimal values.
- `object`: Often used for strings or mixed Python objects.
- `bool`: True or False values.
- `datetime64[ns]`: Date and time values.
- `category`: Values belonging to a limited set of categories.
- `string`: Text values stored using Pandas' string data type.

### Why Are Data Types Important?

Correct data types improve data quality, support valid calculations, and can reduce memory usage.

In AI/ML, categorical and numeric features often require different preprocessing methods.

In [7]:
data = {
    "Name": ["Anu", "Ravi", "Priya"],
    "Age": ["20", "21", "20"],
    "Marks": [85.5, 90.0, 78.5],
    "Passed": [True, True, True]
}

df_types = pd.DataFrame(data)

print("Original data types:")
print(df_types.dtypes)

df_types["Age"] = df_types["Age"].astype(int)

print("\nUpdated data types:")
print(df_types.dtypes)

print("\nAverage age:", df_types["Age"].mean())

Original data types:
Name          str
Age           str
Marks     float64
Passed       bool
dtype: object

Updated data types:
Name          str
Age         int64
Marks     float64
Passed       bool
dtype: object

Average age: 20.333333333333332

## 7. Index and Columns

### Index
The index identifies the rows in a Series or DataFrame. By default, Pandas uses integer labels starting from zero.

### Columns
Columns represent individual variables or features in a DataFrame.

### Custom Index
A custom index can use meaningful labels such as student IDs, product codes, or dates.

### AI/ML Relevance
Column names identify the features used during preprocessing and model training. Index labels help track which observations the data belongs to.

In [8]:
df_index = pd.DataFrame(
    {
        "Name": ["Anu", "Ravi", "Priya"],
        "Marks": [85, 90, 78]
    },
    index=["S101", "S102", "S103"]
)

print(df_index)

print("\nStudent S102:")
print(df_index.loc["S102"])

print("\nColumn names:")
print(df_index.columns.tolist())

       Name  Marks
S101    Anu     85
S102   Ravi     90
S103  Priya     78

Student S102:
Name     Ravi
Marks      90
Name: S102, dtype: object

Column names:
['Name', 'Marks']

### Explanation:
- rename() changes column labels without changing the underlying values.
- reset_index() converts the current index into a regular column and creates a default integer index.

## 8. Reading Data Files with Pandas

Pandas can load data from multiple file formats.

### Common Functions

- `pd.read_csv()` reads CSV files.
- `pd.read_excel()` reads Excel files.
- `pd.read_json()` reads JSON files.
- `pd.read_parquet()` reads Parquet files.
- `pd.read_pickle()` reads Python pickle files.
- `pd.read_sql()` reads data returned by a SQL query.

### Best Practices
- Verify that the file path is correct.
- Inspect the data after loading it.
- Check column names and data types.
- Check for missing and duplicate values.
- Use trusted sources for files, especially pickle files, because loading untrusted pickle data can execute malicious code.

In [9]:
import pandas as pd

sample_data = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Quantity": [5, 20, 12, 7],
    "Price": [55000, 500, 1200, 9000]
})

csv_file = "sample_products.csv"

sample_data.to_csv(csv_file, index=False)

loaded_data = pd.read_csv(csv_file)

print("Data loaded from CSV:")
display(loaded_data)

Data loaded from CSV:

    Product  Quantity  Price
0    Laptop         5  55000
1     Mouse        20    500
2  Keyboard        12   1200
3   Monitor         7   9000

### Explanation:
- to_csv() saves the DataFrame to a CSV file.
- index=False prevents the row index from being saved as an extra column.
- read_csv() loads the file into a new DataFrame.

In [10]:
import pandas as pd

json_file = "sample_products.json"

sample_data.to_json(
    json_file,
    orient="records",
    indent=4
)

json_data = pd.read_json(json_file)

print("Data loaded from JSON:")
display(json_data)

Data loaded from JSON:

    Product  Quantity  Price
0    Laptop         5  55000
1     Mouse        20    500
2  Keyboard        12   1200
3   Monitor         7   9000

### Explanation: 
JSON is commonly used to exchange structured data between applications, web services, and APIs. The records orientation stores each row as a JSON object.

In [11]:
excel_file = "sample_products.xlsx"

try:
    sample_data.to_excel(excel_file, index=False)

    excel_data = pd.read_excel(excel_file)

    print("Data loaded from Excel:")
    display(excel_data)

except ImportError:
    print(
        "Excel support requires openpyxl. "
        "Install it using: %pip install openpyxl"
    )

Data loaded from Excel:

    Product  Quantity  Price
0    Laptop         5  55000
1     Mouse        20    500
2  Keyboard        12   1200
3   Monitor         7   9000

### Explanation:
Excel files are useful for business reports and spreadsheets. Pandas commonly uses openpyxl to read and write .xlsx files.

## 9. Writing Data to Files

Pandas can save DataFrames to files for later use, reporting, sharing, or further processing.

| Function | Purpose |
|---|---|
| `to_csv()` | Save data as CSV |
| `to_excel()` | Save data as Excel |
| `to_json()` | Save data as JSON |
| `to_parquet()` | Save data as Parquet |
| `to_pickle()` | Save a Python object in pickle format |
| `to_sql()` | Write data to a SQL database table |

### Important Notes
- CSV is simple and widely supported.
- Excel is useful for spreadsheet-based workflows.
- JSON is common in APIs and web applications.
- Parquet is a column-oriented format often used for larger analytical datasets.
- Pickle can preserve Python objects but should only be loaded from trusted sources.
- SQL operations require an appropriate database connection and driver.
- Parquet operations usually require an additional engine such as PyArrow.

In [13]:
# Save as CSV
sample_data.to_csv("products_output.csv", index=False)

# Save as JSON
sample_data.to_json(
    "products_output.json",
    orient="records",
    indent=4
)

# Save as Pickle
sample_data.to_pickle("products_output.pkl")

print("Data saved successfully in CSV, JSON, and Pickle formats.")

Data saved successfully in CSV, JSON, and Pickle formats.

## 10. Business Example – Sales Analysis

A company can use Pandas to calculate total sales revenue and identify its best-selling products.

The revenue for each product is calculated as:

**Revenue = Quantity × Price**

This example demonstrates how Pandas supports basic business reporting and decision-making.

In [14]:
sales = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor"],
    "Quantity": [5, 20, 12, 7],
    "Price": [55000, 500, 1200, 9000]
})

sales["Revenue"] = sales["Quantity"] * sales["Price"]

print("Sales report:")
display(sales)

print("Total revenue:", sales["Revenue"].sum())

best_product = sales.loc[sales["Revenue"].idxmax(), "Product"]

print("Product with the highest revenue:", best_product)

Sales report:

    Product  Quantity  Price  Revenue
0    Laptop         5  55000   275000
1     Mouse        20    500    10000
2  Keyboard        12   1200    14400
3   Monitor         7   9000    63000

Total revenue: 362400
Product with the highest revenue: Laptop