# File Operations

## 1. Introduction to File Operations in Pandas

File operations involve reading data from files, processing it, and saving the results for future use.

Pandas provides functions to read and write data in different formats, including CSV, Excel, JSON, Parquet, Pickle, and SQL tables.

### Objectives
- Read and write CSV files.
- Read and write Excel files.
- Work with JSON files.
- Understand Parquet and Pickle formats.
- Read from and write to SQL tables.
- Read multiple files.
- Understand relative and absolute file paths.
- Apply file operations to business and AI/ML datasets.

### Real-World Example
A college can store student information in CSV or Excel files and use Pandas to calculate marks and attendance.

### Business Example
An e-commerce company can read sales records from CSV files, analyze revenue, and save the processed report.

### AI/ML Example
An AI/ML engineer can load training data from a file, clean it, and save the prepared dataset for model training.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.3
NumPy version: 2.4.6

### Explanation:
Pandas handles tabular data, NumPy supports numerical operations, and Path helps work with file paths.

## 2. Creating a Sample Dataset

Before practicing file operations, we will create a sample employee dataset.

This dataset contains employee IDs, names, departments, salaries, and experience. We will use it throughout the notebook to demonstrate reading and writing different file formats.

In [2]:
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Anu", "Ravi", "Priya", "Kiran", "Sneha"],
    "Department": ["AI", "IT", "HR", "AI", "IT"],
    "Salary": [45000, 50000, 40000, 60000, 55000],
    "Experience": [2, 3, 1, 5, 4]
})

display(employees)

   Employee_ID   Name Department  Salary  Experience
0          101    Anu         AI   45000           2
1          102   Ravi         IT   50000           3
2          103  Priya         HR   40000           1
3          104  Kiran         AI   60000           5
4          105  Sneha         IT   55000           4

## 3. CSV File Operations

CSV stands for Comma-Separated Values. It stores tabular data as text, with values separated by commas.

CSV is commonly used to exchange data between applications and to store datasets for data analysis.

### Important Functions
- `pd.read_csv()` reads a CSV file.
- `DataFrame.to_csv()` writes a DataFrame to a CSV file.

### Advantages
- Simple and widely supported.
- Human-readable.
- Suitable for many small and medium-sized datasets.

### Limitations
- Does not reliably preserve data types, formatting, or multiple worksheets.
- Large CSV files can take time to read and write.
- Values containing commas or special characters require proper CSV formatting.

In [3]:
csv_path = Path("employees.csv")

employees.to_csv(csv_path, index=False)

loaded_csv = pd.read_csv(csv_path)

print("CSV file created:", csv_path.exists())
print("\nData read from CSV:")
display(loaded_csv)

CSV file created: True

Data read from CSV:

   Employee_ID   Name Department  Salary  Experience
0          101    Anu         AI   45000           2
1          102   Ravi         IT   50000           3
2          103  Priya         HR   40000           1
3          104  Kiran         AI   60000           5
4          105  Sneha         IT   55000           4

### Explanation:
- to_csv() saves the DataFrame.
- index=False prevents Pandas from saving the row index as an extra column.
- read_csv() loads the data back into a DataFrame.
- exists() checks whether the file exists.

## 4. Excel File Operations

Excel files store tabular data in worksheets and can preserve spreadsheet-specific features such as formatting and formulas.

Pandas supports Excel operations through functions such as `read_excel()` and `to_excel()`.

### Important Functions
- `pd.read_excel()` reads an Excel worksheet.
- `DataFrame.to_excel()` writes a DataFrame to Excel.

The `openpyxl` package is commonly used for `.xlsx` files. Install it if needed using `%pip install openpyxl` in a Jupyter code cell.

In [4]:
excel_path = Path("employees.xlsx")

try:
    employees.to_excel(excel_path, index=False)

    loaded_excel = pd.read_excel(excel_path)

    print("Excel file created:", excel_path.exists())
    display(loaded_excel)

except ImportError:
    print("Install Excel support by running: %pip install openpyxl")

Excel file created: True

   Employee_ID   Name Department  Salary  Experience
0          101    Anu         AI   45000           2
1          102   Ravi         IT   50000           3
2          103  Priya         HR   40000           1
3          104  Kiran         AI   60000           5
4          105  Sneha         IT   55000           4

### Explanation: 
This saves the employee dataset to an Excel file and loads it again. If the required Excel package is missing, install it and rerun the cell.

In [5]:
try:
    with pd.ExcelWriter("employee_report.xlsx", engine="openpyxl") as writer:
        employees.to_excel(
            writer,
            sheet_name="Employees",
            index=False
        )

        employees.groupby("Department")["Salary"].mean().reset_index().to_excel(
            writer,
            sheet_name="Department_Summary",
            index=False
        )

    employee_sheet = pd.read_excel(
        "employee_report.xlsx",
        sheet_name="Employees"
    )

    summary_sheet = pd.read_excel(
        "employee_report.xlsx",
        sheet_name="Department_Summary"
    )

    print("Employee worksheet:")
    display(employee_sheet)

    print("Department summary worksheet:")
    display(summary_sheet)

except ImportError:
    print("Install Excel support by running: %pip install openpyxl")

Employee worksheet:

   Employee_ID   Name Department  Salary  Experience
0          101    Anu         AI   45000           2
1          102   Ravi         IT   50000           3
2          103  Priya         HR   40000           1
3          104  Kiran         AI   60000           5
4          105  Sneha         IT   55000           4

Department summary worksheet:

  Department  Salary
0         AI   52500
1         HR   40000
2         IT   52500

### Explanation: 
ExcelWriter allows multiple DataFrames to be saved as separate worksheets in the same workbook.

## 5. JSON File Operations

JSON stands for JavaScript Object Notation. It is a text-based format used to exchange structured data between applications.

JSON is commonly used by web APIs and applications.

### Important Functions
- `pd.read_json()` reads JSON data.
- `DataFrame.to_json()` writes a DataFrame to JSON.

### Common Orientation
The `records` orientation represents each row as an individual object. This is useful for exchanging row-based data with other applications.

In [6]:
json_path = Path("employees.json")

employees.to_json(
    json_path,
    orient="records",
    indent=4
)

loaded_json = pd.read_json(json_path)

print("JSON file created:", json_path.exists())
display(loaded_json)

JSON file created: True

   Employee_ID   Name Department  Salary  Experience
0          101    Anu         AI   45000           2
1          102   Ravi         IT   50000           3
2          103  Priya         HR   40000           1
3          104  Kiran         AI   60000           5
4          105  Sneha         IT   55000           4

### Explanation:
The DataFrame is stored as a JSON array of records and loaded back into Pandas.

## 6. Parquet File Operations

Parquet is a column-oriented file format designed for efficient data storage and analytical processing.

It is widely used in data engineering, big data systems, and machine learning workflows.

### Important Functions
- `DataFrame.to_parquet()` writes Parquet files.
- `pd.read_parquet()` reads Parquet files.

### Advantages
- Often provides efficient compression.
- Can be faster for analytical workloads.
- Preserves column data types more reliably than CSV.

### Limitations
- Requires an additional engine, such as PyArrow.
- The file is not intended to be edited as plain text.

Install the required package in Jupyter using `%pip install pyarrow` if necessary.

In [7]:
parquet_path = Path("employees.parquet")

try:
    employees.to_parquet(parquet_path, index=False)

    loaded_parquet = pd.read_parquet(parquet_path)

    print("Parquet file created:", parquet_path.exists())
    display(loaded_parquet)

except ImportError:
    print("Install Parquet support by running: %pip install pyarrow")

Parquet file created: True

   Employee_ID   Name Department  Salary  Experience
0          101    Anu         AI   45000           2
1          102   Ravi         IT   50000           3
2          103  Priya         HR   40000           1
3          104  Kiran         AI   60000           5
4          105  Sneha         IT   55000           4

### Explanation:
This writes the DataFrame in Parquet format and reads it back. If PyArrow is not installed, install it and rerun the cell.

## 7. Pickle File Operations

Pickle is a Python serialization format that stores Python objects in a binary file.

Pandas can use Pickle to preserve a DataFrame for later use in Python.

### Important Functions
- `DataFrame.to_pickle()` writes an object.
- `pd.read_pickle()` reads a serialized object.

### Advantages
- Convenient for storing Python objects.
- Often preserves Pandas data types and structure.

### Limitations and Safety
- Pickle is Python-specific and less suitable for exchanging data with other programming languages.
- It may be less portable across different environments and library versions.
- **Never load pickle files from untrusted sources**, because deserialization can execute malicious code.

In [8]:
pickle_path = Path("employees.pkl")

employees.to_pickle(pickle_path)

loaded_pickle = pd.read_pickle(pickle_path)

print("Pickle file created:", pickle_path.exists())
display(loaded_pickle)

Pickle file created: True

   Employee_ID   Name Department  Salary  Experience
0          101    Anu         AI   45000           2
1          102   Ravi         IT   50000           3
2          103  Priya         HR   40000           1
3          104  Kiran         AI   60000           5
4          105  Sneha         IT   55000           4

### Explanation: 
This saves the DataFrame as a serialized Python object and restores it using read_pickle().

## 8. SQL Database Operations

SQL databases store structured data in tables. Pandas can read query results from a database and write DataFrames into database tables.

### Important Functions
- `pd.read_sql()` reads query results.
- `DataFrame.to_sql()` writes a DataFrame to a table.

For this example, we will use SQLite, which is included with Python. It does not require a separate database server.

### Business Example
A company can read employee records from its database, calculate average salaries, and save a report table.

In [9]:
import sqlite3

database_path = "company.db"

with sqlite3.connect(database_path) as connection:
    employees.to_sql(
        "employees",
        connection,
        if_exists="replace",
        index=False
    )

    loaded_sql = pd.read_sql(
        "SELECT * FROM employees",
        connection
    )

print("Data loaded from SQL:")
display(loaded_sql)

Data loaded from SQL:

   Employee_ID   Name Department  Salary  Experience
0          101    Anu         AI   45000           2
1          102   Ravi         IT   50000           3
2          103  Priya         HR   40000           1
3          104  Kiran         AI   60000           5
4          105  Sneha         IT   55000           4

### Explanation:
- sqlite3.connect() creates or opens a SQLite database.
- to_sql() saves the DataFrame into the employees table.
- if_exists="replace" replaces an existing table with the same name.
- read_sql() executes the query and returns the results as a DataFrame.
### Important: 
Use if_exists="replace" carefully because it replaces the existing table. For adding new rows, consider if_exists="append" after checking the table structure.

In [10]:
with sqlite3.connect(database_path) as connection:
    high_salary = pd.read_sql(
        """
        SELECT Name, Department, Salary
        FROM employees
        WHERE Salary >= 50000
        ORDER BY Salary DESC
        """,
        connection
    )

print("Employees with salaries of at least 50000:")
display(high_salary)

Employees with salaries of at least 50000:

    Name Department  Salary
0  Kiran         AI   60000
1  Sneha         IT   55000
2   Ravi         IT   50000

### Explanation:
SQL filters and sorts employee records before returning them as a DataFrame.

## 9. Reading Multiple Files

Sometimes a dataset is split into multiple files, such as monthly sales reports or daily transaction logs.

Pandas can load the files individually and combine them using `pd.concat()`.

### Example
A business may store sales for January and February in separate CSV files. The files can be combined into one DataFrame for analysis.

### Best Practices
- Confirm that the files use consistent column names.
- Check that the column data types match.
- Validate row counts after combining files.
- Handle duplicate records if necessary.
- Use `Path.glob()` to locate files matching a pattern.

In [11]:
from pathlib import Path
import pandas as pd

data_folder = Path("monthly_sales")
data_folder.mkdir(exist_ok=True)

january = pd.DataFrame({
    "Month": ["January", "January"],
    "Product": ["Laptop", "Mouse"],
    "Sales": [100000, 15000]
})

february = pd.DataFrame({
    "Month": ["February", "February"],
    "Product": ["Laptop", "Keyboard"],
    "Sales": [120000, 20000]
})

january.to_csv(data_folder / "sales_january.csv", index=False)
february.to_csv(data_folder / "sales_february.csv", index=False)

csv_files = sorted(data_folder.glob("sales_*.csv"))

monthly_data = pd.concat(
    [pd.read_csv(file) for file in csv_files],
    ignore_index=True
)

print("Files found:", [file.name for file in csv_files])
print("\nCombined sales data:")
display(monthly_data)

Files found: ['sales_february.csv', 'sales_january.csv']

Combined sales data:

      Month   Product   Sales
0  February    Laptop  120000
1  February  Keyboard   20000
2   January    Laptop  100000
3   January     Mouse   15000

### Explanation:
- glob("sales_*.csv") finds matching CSV files.
- pd.read_csv() reads each file.
- pd.concat() combines the rows.
- ignore_index=True creates a fresh sequential index.

## 10. File Paths in Python

A file path tells Python where a file is located.

### Absolute Path
An absolute path gives the complete location of a file, for example:

`C:/Users/YourName/Documents/data.csv`

### Relative Path
A relative path is based on the current working directory, for example:

`data/employees.csv`

### Why Use pathlib?
The `pathlib` module provides an easy way to build and inspect file paths across operating systems.

### Common Mistakes
- Using an incorrect folder name.
- Trying to read a file that does not exist.
- Assuming the current working directory is the notebook's folder.
- Using inconsistent file names or extensions.

In [12]:
from pathlib import Path
import os

print("Current working directory:")
print(os.getcwd())

file_path = Path("employees.csv")

print("\nFile path:", file_path)
print("File exists:", file_path.exists())

if file_path.exists():
    print("File size in bytes:", file_path.stat().st_size)
else:
    print("Check whether the file is saved in the current working directory.")

Current working directory:
C:\Users\giris

File path: employees.csv
File exists: True
File size in bytes: 154

### Explanation:
os.getcwd() shows the current working directory. Path.exists() checks whether the file exists, while stat().st_size reports its size in bytes.

## 11. Business Example – Employee Salary Report

A business can load employee information from a CSV file, calculate average salaries by department, and save the report for management.

This workflow demonstrates how file operations support business reporting and data analysis.

In [13]:
employee_data = pd.read_csv("employees.csv")

department_report = (
    employee_data
    .groupby("Department", as_index=False)
    .agg(
        Employee_Count=("Employee_ID", "count"),
        Average_Salary=("Salary", "mean"),
        Total_Salary=("Salary", "sum")
    )
)

print("Department salary report:")
display(department_report)

department_report.to_csv(
    "department_salary_report.csv",
    index=False
)

print("Department report saved successfully.")

Department salary report:

  Department  Employee_Count  Average_Salary  Total_Salary
0         AI               2         52500.0        105000
1         HR               1         40000.0         40000
2         IT               2         52500.0        105000

Department report saved successfully.

### Explanation:
The code reads employee data, groups it by department, calculates employee counts and salary summaries, and saves the report as CSV.